---
- name: Set the default shell to PowerShell
  ansible.windows.win_regedit:
    path: 'HKLM:\SOFTWARE\OpenSSH'
    name: 'DefaultShell'
    data: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
    type: string
    state: present
  tags:
    - ssh_server

- name: Reset SSH connection after shell change
  ansible.builtin.meta: reset_connection
  tags:
    - ssh_server

- name: Enable public key authentication
  community.windows.win_lineinfile:
    path: 'C:\ProgramData\ssh\sshd_config'
    regex: '^#PubkeyAuthentication yes'
    line: 'PubkeyAuthentication yes'
  tags:
    - ssh_server

- name: Disable strict modes
  community.windows.win_lineinfile:
    path: 'C:\ProgramData\ssh\sshd_config'
    regex: '^#StrictModes yes'
    line: 'StrictModes no'
  tags:
    - ssh_server

- name: Disable administrators_authorized_keys
  when: ssh_server_windows_disableadminauthkeys
  block:
    - name: Comment Match Group administrators
      community.windows.win_lineinfile:
        path: 'C:\ProgramData\ssh\sshd_config'
        regex: '^Match\ Group\ administrators'
        line: '#Match Group administrators'

    - name: Comment Administrators AuthorizedKeysFile
      community.windows.win_lineinfile:
        path: 'C:\ProgramData\ssh\sshd_config'
        regex: '^.*AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys'
        line: '#AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys'
  tags:
    - ssh_server

- name: Deploy Administrators authorized_keys
  ansible.windows.win_copy:
    dest: C:\ProgramData\ssh\administrators_authorized_keys
    content: "{{ ssh_server_windows_adminauthorizedkeys }}"
  tags:
    - ssh_server
